In [2]:
import pandas as pd

titanic_df = pd.read_csv("../cleantitanic_dataset.csv")

titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,initials
0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,0,S,Mr
1,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,1,C,Mrs
2,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,0,S,Miss
3,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,1,S,Mrs
4,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,0,S,Mr

Data Encoding
Data Encoding is a technique that is used to convert categorical columns into numerical ones so that they can be fitted by machine learning models which only take numerical data. It is an important pre-processing step in a machine-learning project.

In [3]:
### Nominal Data  -> data without natural order
titanic_df.Sex

0        male
1      female
2      female
3      female
4        male
        ...
869      male
870    female
871    female
872      male
873      male
Name: Sex, Length: 874, dtype: str

One- Hot Encoding

In [4]:
# Pandas
pd.get_dummies(titanic_df, columns=["Sex","Embarked"], dtype=int).head(5)

,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,initials,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.0,3.0,"Braund, Mr. Owen Harris",22.0,1.0,0.0,A/5 21171,7.2500,0,Mr,0,1,0,0,1
1,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1.0,0.0,PC 17599,71.2833,1,Mrs,1,0,1,0,0
2,1.0,3.0,"Heikkinen, Miss. Laina",26.0,0.0,0.0,STON/O2. 3101282,7.9250,0,Miss,1,0,0,0,1
3,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1.0,0.0,113803,53.1000,1,Mrs,1,0,0,0,1
4,0.0,3.0,"Allen, Mr. William Henry",35.0,0.0,0.0,373450,8.0500,0,Mr,0,1,0,0,1

In [5]:
# !pip install scikit-learn
import sklearn
sklearn.show_versions()

System:
    python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
executable: c:\Users\ACER\AppData\Local\Python\pythoncore-3.14-64\python.exe
   machine: Windows-11-10.0.26200-SP0

Python dependencies:
      sklearn: 1.9.0
          pip: 26.2.1
   setuptools: 84.0.0
        numpy: 2.5.2
        scipy: 1.18.1
       Cython: None
       pandas: 3.0.5
   matplotlib: 3.11.1
       joblib: 1.6.0
threadpoolctl: 3.6.0
     narwhals: 2.25.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libscipy_openblas
       filepath: C:\Users\ACER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy.libs\libscipy_openblas64_-327b2e0bcffce2882e0dc04cdeb4eaa6.dll
        version: 0.3.34.0.0
threading_layer: pthreads
   architecture: Haswell

       user_api: openmp
   internal_api: openmp
    num_threads: 12
         prefix: vcomp
       filepath: C:\Users\ACER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libscipy_openblas
       filepath: C:\Users\ACER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\scipy.libs\libscipy_openblas-197ee2fc9b4d071f7e048078cac74115.dll
        version: 0.3.31.dev
threading_layer: pthreads
   architecture: Haswell